version: '3'

services:
  web:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    command: npm start

  doc:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - '8080:8080'
    command: npm run doc
