/* eslint-disable no-shadow */
export enum ActionTypes {
  GET_FORECAST_COLLECTION_REQUEST = '@collection/GET_FORECAST_COLLECTION_REQUEST',
  GET_FORECAST_COLLECTION_SUCCESS = '@collection/GET_FORECAST_COLLECTION_SUCCESS',
  GET_FORECAST_COLLECTION_FAILURE = '@collection/GET_FORECAST_COLLECTION_FAILURE',
}
