/* eslint-disable no-shadow */
export enum ActionTypes {
  GET_CURRENT_FORECAST_REQUEST = '@current/GET_CURRENT_FORECAST_REQUEST',
  GET_CURRENT_FORECAST_SUCCESS = '@current/GET_CURRENT_FORECAST_SUCCESS',
  GET_CURRENT_FORECAST_FAILURE = '@current/GET_CURRENT_FORECAST_FAILURE',
}
